export const labels = {
    managers: 'مدیران عامل',
    lastManagers: ' مدیران عامل گذشته',
    date: 'انتخاب تاریخ',
    fullName: 'نام و نام خانوادگی',
    workStartDate: 'تاریخ شروع به کار',
    searchItem: 'آیتم های جستجو',
    nationalCode: 'کدملی',
    changeManager: 'تغییر مدیرعامل',
    search: 'جستجو',
    manager: 'مدیرعامل',
    succeed: 'عملیات با موفقیت انجام شد',
    unsucceed: 'خطا در انجام عملیات',
    directorBoard: 'هیئت مدیره',
    founderGroup: 'هیئت موسس',
    directorBoardMember: 'اعضای هیئت مدیره',
    founderGroupMember: 'اعضای هیئت موسس',
    delete: 'حذف',
    addDirector: 'افزودن فرد',
    dataNotFound: 'نتیجه ای یافت نشد',
    activity: 'فعالیت ها',
    learning: 'آموزشی',
    advertise: 'تبلیغی',
    research: 'پژوهشی',
    learningActivity: 'فعالیت های آموزشی',
    trainingCourse: 'دوره های آموزشی',
    courseTitle: 'عنوان دوره',
    officeCode: 'کد موسسه',
    addCoach: 'افزودن مربی',
    validation: {
        mandatory: 'این فیلد اجباریست'
    }
}