export const labels = {
    managers: 'مدیران عامل',
    date: 'انتخاب تاریخ',
    fullName: 'نام و نام خانوادگی',
    workStartDate: 'تاریخ شروع به کار',
    searchItem: 'آیتم های جستجو',
    nationalCode: 'کدملی',
    changeManager: 'تغییر مدیرعامل',
    search: 'جستجو',
    manager: 'مدیرعامل',
    succeed: 'عملیات با موفقیت انجام شد',
    unsucceed: 'خطا در انجام عملیات',
    directorBoard: 'هیئت مدیره',
    founderGroup: 'هیئت موسس',
    directorBoardMember: 'اعضای هیئت مدیره',
    founderGroupMember: 'اعضای هیئت موسس',
    delete: 'حذف',
    addDirector: 'افزودن فرد',
    dataNotFound: 'نتیجه ای یافت نشد'
}