export const labels = {
    managers: 'مدیران عامل',
    lastManagers: ' مدیران عامل گذشته',
    date: 'انتخاب تاریخ',
    fullName: 'نام و نام خانوادگی',
    workStartDate: 'تاریخ شروع به کار',
    searchItem: 'آیتم های جستجو',
    nationalCode: 'کدملی',
    changeManager: 'تغییر مدیرعامل',
    search: 'جستجو',
    manager: 'مدیرعامل',
    succeed: 'عملیات با موفقیت انجام شد',
    unsucceed: 'خطا در انجام عملیات',
    directorBoard: 'هیئت مدیره',
    founderGroup: 'هیئت موسس',
    directorBoardMember: 'اعضای هیئت مدیره',
    founderGroupMember: 'اعضای هیئت موسس',
    delete: 'حذف',
    addDirector: 'افزودن فرد',
    dataNotFound: 'نتیجه ای یافت نشد',
    activity: 'فعالیت ها',
    learning: 'آموزشی',
    advertise: 'تبلیغی',
    research: 'پژوهشی',
    learningActivity: 'فعالیت های آموزشی',
    trainingCourse: 'دوره های آموزشی',
    courseTitle: 'عنوان دوره',
    officeCode: 'کد موسسه',
    addCoach: 'افزودن مربی',
    recentCertificate: 'سوابق گواهی',
    printCert: 'صدور گواهی',
    validation: {
        mandatory: 'این فیلد اجباریست'
    },
    teacherNatCode: "کد ملی مربی",
    registerClass: "ثبت کلاس",
    memberNum: "تعداد",
    town: "شهرستان",
    gender: 'جنسیت',
    classLevel: 'سطح کلاس',
    dore: "دوره",
    setScore: "ثبت نمره",
    midScore: 'نمره میان دوره',
    finalScore: 'نمره  پایانی',
    addStudent: 'افزودن دانش آموز',
    mobile: 'شماره همراه',
    endCoWorkDate: 'تاریخ پایان همکاری',
    startCoWorkDate: 'تاریخ آغاز همکاری',
    startClassHour: 'ساعت شروع کلاس',
    startClassMinute: 'دقیقه شروع کلاس',
    endClassHour: 'ساعت پایان کلاس',
    endClassMinute: 'دقیقه پایان کلاس',
    update: 'به روزرسانی',
    confirm: 'تایید ',
    insurance: 'بیمه فعالان قرآنی'
}